from utils import initialize_feature_extractor, get_features, load_model
from metrics import compute_precision_recall_manifold, compute_fid
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

import os
import argparse
import numpy as np
from PIL import Image

# ===================================================================================================================
#                                             Feature Extractor
# ===================================================================================================================

# 1. Load the Feature Extractor (CNN model pre-trained on MNIST)
# If not found, run 'python train_feature_extractor.py' to train it and save the weights.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
feature_extractor = initialize_feature_extractor(device=device, path='checkpoints/cnn_mnist_features_extractor.pkl')

# =====================================================================
#                           ARGUMENT PARSER
# =====================================================================

parser = argparse.ArgumentParser(description="Evaluate generated samples")
parser.add_argument(
    "--samples_dir",
    type=str,
    default="samples",
    help="Directory containing generated .png images"
)

args = parser.parse_args()
SAMPLES_DIR = args.samples_dir

print(f"📂 Using samples directory: {SAMPLES_DIR}")

# ===================================================================================================================
#                                             BASELINE GENERATOR EVALUATION     
# ===================================================================================================================

# 2a. Load real images (MNIST test set)
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
test_dataset = datasets.MNIST(root='data', train=False, download=True, transform=transform)
test_loader = DataLoader(test_dataset, batch_size=10000, shuffle=False)
real_images_tensor, _ = next(iter(test_loader))  # (10000, 1, 28, 28)

# 2b. Load images generated by generate.py, convert them to tensors, and stack them into fake_images_tensor
fake_images = []
for filename in sorted(os.listdir(SAMPLES_DIR), key=lambda x: int(x.split('.')[0])):
    if filename.endswith('.png'):
        img_path = os.path.join(SAMPLES_DIR, filename)
        img = Image.open(img_path).convert('L')  # Convert to grayscale
        img_tensor = transform(img)  # Apply the same transformations as for real images
        fake_images.append(img_tensor)
fake_images_tensor = torch.stack(fake_images)  # (10000, 1, 28, 28)

# 3. Feature extraction
print("Extracting features...")

# --- Features for Precision & Recall (normalized) ---
real_feats_pr = get_features(
    feature_extractor,
    real_images_tensor,
    device=device,
    normalize=True
)

fake_feats_pr = get_features(
    feature_extractor,
    fake_images_tensor,
    device=device,
    normalize=True
)

# --- Features for FID (NOT normalized) ---
real_feats_fid = get_features(
    feature_extractor,
    real_images_tensor,
    device=device,
    normalize=False
)

fake_feats_fid = get_features(
    feature_extractor,
    fake_images_tensor,
    device=device,
    normalize=False
)

# 4. Compute Precision, Recall, and FID
print("Computing metrics...")

# Precision and Recall (use normalized features)
precision, recall = compute_precision_recall_manifold(real_feats_pr, fake_feats_pr, k=3)
p, r = compute_precision_recall_manifold(real_feats_pr, real_feats_pr, k=3)
pf, rf = compute_precision_recall_manifold(fake_feats_pr, fake_feats_pr, k=3)

# FID (use raw features)
fid_value = compute_fid(real_feats_fid, fake_feats_fid)

folder_name = os.path.basename(SAMPLES_DIR)
if "js" in folder_name.lower():
    model_name = "f-GAN JS"
elif "kl" in folder_name.lower():
    model_name = "f-GAN KL"
elif "pearson" in folder_name.lower():
    model_name = "f-GAN Pearson"
elif "baseline" in folder_name.lower():
    model_name = "Baseline Generator"
else:
    model_name = "Unknown Generator"

print(f"[{model_name}] -> FID: {fid_value:.4f} | Precision: {precision:.4f} | Recall: {recall:.4f}")